<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*SQL SERVER*/
$active_group='ncserver';
$active_record=TRUE;
$db['ncserver']['hostname']='localhost';
$db['ncserver']['username']='sa';
$db['ncserver']['password']='sql';
$db['ncserver']['database']='PORTALBIZ';
$db['ncserver']['dbdriver']='sqlsrv';
#$db['ncserver']['port']='';
$db['ncserver']['dbprefix']='';
$db['ncserver']['pconnect']=FALSE;
$db['ncserver']['db_debug']=TRUE;
$db['ncserver']['cache_on']=FALSE;
$db['ncserver']['cachedir']='';
$db['ncserver']['char_set']='utf8';
$db['ncserver']['dbcollat']='utf8_general_ci';
$db['ncserver']['swap_pre']='';
$db['ncserver']['autoinit']=TRUE;
$db['ncserver']['stricton']=FALSE;
